import './globals.css';
import type { Metadata } from 'next';
import { ThemeProviders, ToasterProviders } from '@/components';
import { poppins } from '@/config/fonts';
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="bg-white dark:bg-neutral-900"
    >
      <body className={poppins.className}>
        <ThemeProviders>
          <ToasterProviders>{children}</ToasterProviders>
        </ThemeProviders>
        <Analytics />
      </body>
    </html>
  );
}
